package ma.dev.workflow.issue.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;
import ma.dev.workflow.issue.models.enums.IssueType;
import ma.dev.workflow.issue.models.enums.Priority;
import ma.dev.workflow.issue.models.enums.Status;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@Setter
public class IssueDTO {

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /** Generated by the server from the project key. */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String issueKey;

    @NotBlank(message = "Title is required")
    @Size(max = 255, message = "Title must be at most 255 characters")
    private String title;

    private String description;

    @NotNull(message = "Issue type is required")
    private IssueType type;

    /** Set to TO_DO on creation. Changed only through PATCH /issues/{id}/status. */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Status status;

    @NotNull(message = "Priority is required")
    private Priority priority;

    @NotNull(message = "Project id is required")
    private Long projectId;

    private Long boardId;

    /** Null means the backlog. */
    private Long sprintId;

    /**
     * Taken from the token, never from the request. Sending it has no effect: whoever holds the
     * token is the reporter. Before M2 this was a writable field, which meant any caller could
     * file an issue in someone else's name.
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long reporterId;

    private Long assigneeId;

    private LocalDate dueDate;

    /** Sent back so the client can return it on the next update and detect a conflict. */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long version;

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private LocalDateTime createdAt;
}
